// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Plainion.RI")]
[assembly: AssemblyProductAttribute("Plainion.Windows.Editors")]
[assembly: AssemblyDescriptionAttribute("Plainion.Windows.Editors")]
[assembly: AssemblyCopyrightAttribute("Copyright @ 2017")]
[assembly: AssemblyVersionAttribute("1.2.0")]
[assembly: AssemblyFileVersionAttribute("1.2.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Plainion.RI";
        internal const System.String AssemblyProduct = "Plainion.Windows.Editors";
        internal const System.String AssemblyDescription = "Plainion.Windows.Editors";
        internal const System.String AssemblyCopyright = "Copyright @ 2017";
        internal const System.String AssemblyVersion = "1.2.0";
        internal const System.String AssemblyFileVersion = "1.2.0";
    }
}
